version: '3'
services:
  app:
    container_name: application
    build: "./frontend/"
    ports:
      - "4001:4000"
    networks:
      - myNetWork
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    container_name: processor
    build: "./backend/"
    ports:
      - "3001:3000"
    hostname: "server"
    networks:
      - myNetWork
    volumes:
      - "./backend:/great/src/app" 
  database:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017" 
    volumes:
      - "myVolume:/data/db"
    networks:
      - myNetWork

volumes:
  myVolume:

networks:
  myNetWork:
    driver: bridge
